config/routes.rb
Rails.application.routes.draw do

  root 'page#welcome'
  get '/about' => 'page#about'

  resources :issues

  post '/issues/:issue_id/comments' => 'comments#create'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :issue

  def user_avatar
    gravatar_id = Digest::MD5.hexdigest(self.email.downcase)
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=512&d=retro"
  end
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    c = Comment.new
    c.username = params[:username]
    c.email = params[:email]
    c.content = params[:content]
    c.issue_id = params[:issue_id]
    c.save
    redirect_to c.issue
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  def show
    @issue = Issue.find(params[:id])
    @comments = @issue.comments
  end

  def new
    @issue = Issue.new
  end

  def create
    @issue = Issue.new(issue_params)
    @issue.save
    # 以上两行教程的原文是：Issue.create(issue_params)
    redirect_to :root
    # render plain: params[:issue].inspect测试用
  end

  def destroy
    issue = Issue.find(params[:id])
    issue.destroy
    redirect_to :root
  end

  def edit
    @issue = Issue.find(params[:id])
  end

  def update
    i = Issue.find(params[:id])
    i.update_attributes(issue_params)
    redirect_to :root
  end

  private

  def issue_params
    params.require(:issue).permit(:title, :content)
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def welcome
    @issues = Issue.all.reverse
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/issues/_form.html.erb
<div class="new-issue-form-container clearfix">
  <div class="new-issue-form clearfix">
    <%= form_for issue do |f| %>
      <dl class="form">
        <dt><%= f.label :title %></dt>
        <dd><%= f.text_field :title %></dd>
      </dl>
      <dl class="form">
        <dt><%= f.label :content %></dt>
        <dd><%= f.text_area :content %></dd>
      </dl>
      <p><%= f.submit :class => "submit-issue-button btn btn-primary" %></p>
    <% end %>
  </div>
</div>

app/views/issues/edit.html.erb
<%= render partial: 'form', locals: {issue: @issue} %>

app/views/issues/new.html.erb
<div class="new-issue-form-container clearfix">
  <div class="new-issue-form clearfix">
    <%= form_for @issue do |f| %>
      <dl class="form">
        <dt><%= f.label :title %></dt>
        <dd><%= f.text_field :title %></dd>
      </dl>
      <dl class="form">
        <dt><%= f.label :content %></dt>
        <dd><%= f.text_area :content %></dd>
      </dl>
      <p><%= f.submit "发布新活动", :class => "submit-issue-button btn btn-primary" %></p>
    <% end %>
  </div>
</div>

app/views/issues/show.html.erb
<div class="issue-heading">
  <div class="container">
    <%= @issue.title %>
    <%= link_to 'Destroy', issue_path(@issue), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary" %>
    <%= link_to 'edit', edit_issue_path(@issue), class: "btn btn-primary" %>
  </div>
</div>
<div class="container">
  <div class="replies">
    <article class="reply clearfix">
      <div class="avatar">
        <img src="http://en.gravatar.com/userimage/99519790/160f0fbca56510765f78b32b7de6ad94.jpg;d=retr" alt="" class="image-circle">
      </div>
      <div class="body">
        <div class="heading">
          <h5 class="name">
            <a href="#">dycalc</a>
          </h5>
        </div>
        <%= @issue.content %>
      </div>
    </article>
    <%= render partial: 'shared/comment_list', locals: {comments: @comments} %>
    <%= render partial: 'shared/comment_box', locals: {issue: @issue} %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
	<%= stylesheet_link_tag "application" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
</head>
<body class="<%= params[:controller] + '-' + params[:action] %>">
	<div class="navbar clearfix">
		<div class="container">
			<a class="navbar-brand" href="/">
				Meetup
			</a>
			<ul class="nav left">
				<li><%= link_to "About", "/about" %></li>
				<li><a href="#">placeholder</a></li>
			</ul>
			<ul class="nav right">
				<li><a href="#">login</a></li>
				<li><a href="#">signup</a></li>
			</ul>
		</div>
	</div>

<%= yield %>

	<div class="footer">
		<div class="container">
			footer
		</div>
	</div>
	<script>
		$('.home-banner').anystretch();
	</script>
</body>
</html>

app/views/page/_issue_list.html.erb
<div class="issue-list">
  <% issues.each do |i| %>
    <article class="issue clearfix">
      <div class="avatar">
        <a href="/happypeter">
          <img src=http://en.gravatar.com/userimage/99519790/160f0fbca56510765f78b32b7de6ad94.jpg;d=retro alt="">
        </a>
      </div>
      <div class="body">
        <h5 class="title">
          <!-- 这里看不懂啊 -->
          <%= link_to i.title, issue_path(i) %>
          <!-- <%= link_to i.title, "/issues/#{i.id}" %> -->
        </h5>
        <a class="read-more" href="#">read</a>
        <span class="meta-data">
          <a href="/dycalc">dycalc</a>
          <%= time_ago_in_words(i.created_at) %> ago
        </span>
      </div>
      <div class="issue-comment-count">
        <i class="fa fa-comments icon-muted"></i>
        <%= link_to i.comments.count, i %>
      </div>
    </article>
  <% end %>
</div>

app/views/page/about.html.erb
	<div class="container">
		<h1>about</h1>
	</div>

app/views/page/welcome.html.erb
	<div class="home-banner" data-stretch="<%= image_url "home-banner-bg.jpg" %>">
		<div class="banner-inner container clearfix">
		  <h1>It's Party Time!</h1>
		  <p class="subheading">到时聚聚，聊聊程序</p>
		  <div class="home-banner-links">
		    <%= link_to "发布新活动", "/issues/new", class: "banner-btn btn" %>
		  </div>
		</div>
	</div>

	<div class="issue-list-header">
	  <div class="container clearfix">
	    <h1 class="issue-list-heading">所有活动都在下面了...</h1>
	  </div>
	</div>

	<div class="container clearfix">
  <%= render partial: 'issue_list', locals: { issues: @issues } %>
</div>

	<script>
		$('.home-banner').anystretch();
	</script>

app/views/shared/_comment_box.html.erb
<article class="reply clearfix">
  <div class="avatar">
    <%= link_to "#" do %>
      <%= image_tag "default_avatar.png", class: "image-circle" %>
    <% end %>
  </div>
  <div class="body">
  <%= form_tag("/issues/#{issue.id}/comments", method: :post) do  %>
    <%= label_tag :username, "用户名" %>
    <%= text_field_tag(:username) %>
    <%= label_tag :email, "邮箱" %>
    <%= text_field_tag(:email) %>
    <%= text_area_tag(:content) %>
    <%= submit_tag '提交评论', class: 'btn btn-primary btn-submit' %>
  <% end %>
  </div>
</article>

app/views/shared/_comment_list.html.erb
<% comments.each do |c| %>
    <div class="reply clearfix">
       <div class="avatar">
         <%= link_to '#' do %>
           <%= image_tag c.user_avatar, class: 'image-circle' %>
         <% end %>
       </div>
       <div class="body">
         <div class="heading">
            <h5 class="name"><%= link_to c.username, "#" %></h5>
            <span class="datetime">
              <%= time_ago_in_words c.created_at %> ago
            </span>
         </div>
         <%= c.content %>
       </div>
    </div>
  <% end %>